### ISSUE TITLE
question about S4LRU

### ISSUE THREAD

**Issue by gzanwpu** [1a1a11a/PyMimircache#14]
Hi, I'm trying to simulate s4lru on trace, but it seems doesn't work, Is there something wrong with my usage？
here is my code and the error:
-------------------------------------------------
from PyMimircache import *
c = Cachecow()
c.open('trace.txt')
profiler = c.profiler('S4LRU', cache_size=2000, bin_size=100)
profiler.plotHRC()

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/PyMimircache/profiler/pyGeneralProfiler.py", line 59, in _cal_hit_count_subprocess
    hit = process_cache.access(req, )
  File "/usr/local/lib/python3.6/dist-packages/PyMimircache/cache/s4lru.py", line 110, in access
    self._update(req_item, )
  File "/usr/local/lib/python3.6/dist-packages/PyMimircache/cache/s4lru.py", line 52, in _update
    req_item, self.fourth_lru, self.third_lru)
  File "/usr/local/lib/python3.6/dist-packages/PyMimircache/cache/s4lru.py", line 65, in _move_to_upper_level
    node = lowerLRU.cache_dict[element]
AttributeError: 'LRU' object has no attribute 'cache_dict'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/PycharmProjects/cache_simulation/test.py", line 5, in <module>
    profiler.plotHRC()
  File "/usr/local/lib/python3.6/dist-packages/PyMimircache/profiler/pyGeneralProfiler.py", line 201, in plotHRC
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/PyMimircache/profiler/pyGeneralProfiler.py", line 140, in _run
    result = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: 'LRU' object has no attribute 'cache_dict'

thank u !

**Comment by 1a1a11a** [comment]
Hi there, 
    Are you using the pypi version or github version? The github version might be broken. You can install the pypi version via `pip3 install pyMimircache` 

BTW, if you are fine working with C, we have an internal version wich runs 20x faster and support different object sizes, I can share the test version with you if interested.

**Comment by gzanwpu** [comment]
I follow the guildlines to install pyMimircache by pip. BTW, I want to use it to verify the effectiveness of my caching strategy and I saw some interesting caching algorithm like mithril, amp. But when i trying to use it, i meet some error. I didn't see it in guildlines, so, i guess it maybe the test version.  i want to know how can i get the correct simulation result about that.  if it works, That will mean a lot to me. Thank you.

**Comment by 1a1a11a** [comment]
Hmm, that's not right, I will take a look. The other algorithms (Mithril and AMP) are no longer officially supported, but the code is included for reference.

**Comment by gzanwpu** [comment]
OK， Thank U very much!!
