### ISSUE TITLE
some errors when I play cache prefetching

### ISSUE THREAD

**Issue by zztaki** [1a1a11a/PyMimircache#17]
It seems that `libcachesim` doesn't support cache prefetching such as `amp`, `pg` and `mithril` so I play using `PyMimirCache`. But I receive some errors.

I install `PyMimircache` using `python3 setup.py install` and the process is as follows.

```
CMimircache components CMimircache.CacheReader, CMimircache.LRUProfiler, CMimircache.GeneralProfiler, CMimircache.Heatmap import failed, performance will degrade, reason: No module named 'PyMimircache.CMimircache.LRUProfiler', No module named 'PyMimircache.CMimircache.CacheReader', No module named 'PyMimircache.CMimircache.Heatmap', No module named 'PyMimircache.CMimircache.GeneralProfiler', ignore this warning if this is installation
CMimircache is not successfully installed, modules beginning with C are all disabled
not all plots in twoDPlots support Py mode
/home/zzl/local/anaconda3/lib/python3.9/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running install
/home/zzl/local/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/zzl/local/anaconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing PyMimircache.egg-info/PKG-INFO
writing dependency_links to PyMimircache.egg-info/dependency_links.txt
writing requirements to PyMimircache.egg-info/requires.txt
writing top-level names to PyMimircache.egg-info/top_level.txt
reading manifest file 'PyMimircache.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'multiMachineProcessing'
adding license file 'LICENSE'
adding license file 'AUTHORS'
writing manifest file 'PyMimircache.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/PyMimircache
creating build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/binaryWriter.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/__init__.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/requestItem.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/vscsiReader.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/plainReader.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/csvReader.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/binaryReader.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/traceStat.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/multiReader.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cacheReader/abstractReader.py -> build/bdist.linux-x86_64/egg/PyMimircache/cacheReader
copying build/lib.linux-x86_64-cpython-39/PyMimircache/version.py -> build/bdist.linux-x86_64/egg/PyMimircache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/c_eviction_stat.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/PyMimircache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/__init__.py -> build/bdist.linux-x86_64/egg/PyMimircache
creating build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/cLRUProfiler.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/twoDPlots.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/cHeatmap.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/profilerUtils.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/pyHeatmap.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/cGeneralProfiler.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/pyLRUProfiler.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/__init__.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/pyHeatmapAux.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/pyTimeProfiler.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/pyGeneralProfiler.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler
creating build/bdist.linux-x86_64/egg/PyMimircache/profiler/utils
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/utils/__init__.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler/utils
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/utils/splay.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler/utils
copying build/lib.linux-x86_64-cpython-39/PyMimircache/profiler/utils/dist.py -> build/bdist.linux-x86_64/egg/PyMimircache/profiler/utils
creating build/bdist.linux-x86_64/egg/PyMimircache/CMimircache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/CMimircache/CacheReader.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/PyMimircache/CMimircache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/CMimircache/Heatmap.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/PyMimircache/CMimircache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/CMimircache/GeneralProfiler.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/PyMimircache/CMimircache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/CMimircache/LRUProfiler.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/PyMimircache/CMimircache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/const.py -> build/bdist.linux-x86_64/egg/PyMimircache
creating build/bdist.linux-x86_64/egg/PyMimircache/top
copying build/lib.linux-x86_64-cpython-39/PyMimircache/top/cachecow.py -> build/bdist.linux-x86_64/egg/PyMimircache/top
copying build/lib.linux-x86_64-cpython-39/PyMimircache/top/__init__.py -> build/bdist.linux-x86_64/egg/PyMimircache/top
creating build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/mru.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/secondChance.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/abstractCache.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/fifo.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/randomv0.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/__init__.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/lru.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/clock.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/slru.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/cacheLine.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/arc.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/random.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/s4lru.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
copying build/lib.linux-x86_64-cpython-39/PyMimircache/cache/optimal.py -> build/bdist.linux-x86_64/egg/PyMimircache/cache
creating build/bdist.linux-x86_64/egg/PyMimircache/utils
copying build/lib.linux-x86_64-cpython-39/PyMimircache/utils/linkedList.py -> build/bdist.linux-x86_64/egg/PyMimircache/utils
copying build/lib.linux-x86_64-cpython-39/PyMimircache/utils/__init__.py -> build/bdist.linux-x86_64/egg/PyMimircache/utils
copying build/lib.linux-x86_64-cpython-39/PyMimircache/utils/randomdict.py -> build/bdist.linux-x86_64/egg/PyMimircache/utils
copying build/lib.linux-x86_64-cpython-39/PyMimircache/utils/printing.py -> build/bdist.linux-x86_64/egg/PyMimircache/utils
copying build/lib.linux-x86_64-cpython-39/PyMimircache/utils/timer.py -> build/bdist.linux-x86_64/egg/PyMimircache/utils
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/binaryWriter.py to binaryWriter.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/requestItem.py to requestItem.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/vscsiReader.py to vscsiReader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/plainReader.py to plainReader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/csvReader.py to csvReader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/binaryReader.py to binaryReader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/traceStat.py to traceStat.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/multiReader.py to multiReader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cacheReader/abstractReader.py to abstractReader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/version.py to version.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/cLRUProfiler.py to cLRUProfiler.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/twoDPlots.py to twoDPlots.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/cHeatmap.py to cHeatmap.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/profilerUtils.py to profilerUtils.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/pyHeatmap.py to pyHeatmap.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/cGeneralProfiler.py to cGeneralProfiler.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/pyLRUProfiler.py to pyLRUProfiler.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/pyHeatmapAux.py to pyHeatmapAux.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/pyTimeProfiler.py to pyTimeProfiler.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/pyGeneralProfiler.py to pyGeneralProfiler.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/utils/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/utils/splay.py to splay.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/profiler/utils/dist.py to dist.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/const.py to const.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/top/cachecow.py to cachecow.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/top/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/mru.py to mru.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/secondChance.py to secondChance.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/abstractCache.py to abstractCache.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/fifo.py to fifo.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/randomv0.py to randomv0.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/lru.py to lru.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/clock.py to clock.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/slru.py to slru.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/cacheLine.py to cacheLine.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/arc.py to arc.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/random.py to random.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/s4lru.py to s4lru.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/cache/optimal.py to optimal.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/utils/linkedList.py to linkedList.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/utils/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/utils/randomdict.py to randomdict.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/utils/printing.py to printing.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/utils/timer.py to timer.cpython-39.pyc
creating stub loader for PyMimircache/CMimircache/CacheReader.cpython-39-x86_64-linux-gnu.so
creating stub loader for PyMimircache/CMimircache/LRUProfiler.cpython-39-x86_64-linux-gnu.so
creating stub loader for PyMimircache/CMimircache/GeneralProfiler.cpython-39-x86_64-linux-gnu.so
creating stub loader for PyMimircache/CMimircache/Heatmap.cpython-39-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/CMimircache/CacheReader.py to CacheReader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/CMimircache/LRUProfiler.py to LRUProfiler.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/CMimircache/GeneralProfiler.py to GeneralProfiler.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyMimircache/CMimircache/Heatmap.py to Heatmap.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying PyMimircache.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyMimircache.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyMimircache.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyMimircache.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyMimircache.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
PyMimircache.CMimircache.__pycache__.CacheReader.cpython-39: module references __file__
PyMimircache.CMimircache.__pycache__.GeneralProfiler.cpython-39: module references __file__
PyMimircache.CMimircache.__pycache__.Heatmap.cpython-39: module references __file__
PyMimircache.CMimircache.__pycache__.LRUProfiler.cpython-39: module references __file__
PyMimircache.utils.__pycache__.printing.cpython-39: module MAY be using inspect.getframeinfo
PyMimircache.utils.__pycache__.timer.cpython-39: module references __file__
creating 'dist/PyMimircache-0.0.2.103-py3.9-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing PyMimircache-0.0.2.103-py3.9-linux-x86_64.egg
removing '/home/zzl/local/anaconda3/lib/python3.9/site-packages/PyMimircache-0.0.2.103-py3.9-linux-x86_64.egg' (and everything under it)
creating /home/zzl/local/anaconda3/lib/python3.9/site-packages/PyMimircache-0.0.2.103-py3.9-linux-x86_64.egg
Extracting PyMimircache-0.0.2.103-py3.9-linux-x86_64.egg to /home/zzl/local/anaconda3/lib/python3.9/site-packages
PyMimircache 0.0.2.103 is already the active version in easy-install.pth

Installed /home/zzl/local/anaconda3/lib/python3.9/site-packages/PyMimircache-0.0.2.103-py3.9-linux-x86_64.egg
Processing dependencies for PyMimircache==0.0.2.103
Searching for numpy==1.22.3
Best match: numpy 1.22.3
Adding numpy 1.22.3 to easy-install.pth file
Installing f2py script to /home/zzl/local/anaconda3/bin
Installing f2py3 script to /home/zzl/local/anaconda3/bin
Installing f2py3.9 script to /home/zzl/local/anaconda3/bin

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for matplotlib==3.5.1
Best match: matplotlib 3.5.1
Adding matplotlib 3.5.1 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for mmh3==4.0.1
Best match: mmh3 4.0.1
Adding mmh3 4.0.1 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for HeapDict==1.0.1
Best match: HeapDict 1.0.1
Adding HeapDict 1.0.1 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for python-dateutil==2.8.2
Best match: python-dateutil 2.8.2
Adding python-dateutil 2.8.2 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for pyparsing==3.0.8
Best match: pyparsing 3.0.8
Adding pyparsing 3.0.8 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for Pillow==9.1.0
Best match: Pillow 9.1.0
Adding Pillow 9.1.0 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for packaging==21.3
Best match: packaging 21.3
Adding packaging 21.3 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for kiwisolver==1.4.2
Best match: kiwisolver 1.4.2
Adding kiwisolver 1.4.2 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for fonttools==4.32.0
Best match: fonttools 4.32.0
Adding fonttools 4.32.0 to easy-install.pth file
Installing fonttools script to /home/zzl/local/anaconda3/bin
Installing pyftmerge script to /home/zzl/local/anaconda3/bin
Installing pyftsubset script to /home/zzl/local/anaconda3/bin
Installing ttx script to /home/zzl/local/anaconda3/bin

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for cycler==0.11.0
Best match: cycler 0.11.0
Adding cycler 0.11.0 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using /home/zzl/local/anaconda3/lib/python3.9/site-packages
Finished processing dependencies for PyMimircache==0.0.2.103

**Comment by zztaki** [comment]
And then I play prefetching like that
```python3
from PyMimircache import *

DEFAULT_PARAM = {"max_support": 8,
                 "min_support": 2,
                 "confidence": 0,
                 "item_set_size": 20,
                 "prefetch_list_size": 2,
                 "cache_type": "LRU",
                 "sequential_type": 0,
                 "max_metadata_size": 0.1,
                 "block_size": 64 * 1024,
                 "sequential_K": 0,
                 "cycle_time": 2,
                 "AMP_pthreshold": 256
                }

def run(dat):
    reader = PlainReader(dat, data_type='l')
    size = reader.get_num_of_uniq_req() // 5
    print("cache size {}".format(size))
    # "mithril", "amp", "pg",
    p = CGeneralProfiler(reader, "mimir", size, bin_size=size,
                         cache_params=DEFAULT_PARAM, num_of_threads=1)
    hr = p.get_hit_rate()
    return hr

print(run("../data/trace.txt"))

**Comment by zztaki** [comment]
for `mimir`,  I receive
```
cache size 9794
Segmentation fault (core dumped)
```

for `mithril`, I receive
```
cache size 9794
0.00%

cache size 9794, real size: 9511, hit rate 0.275090, total check 0, Mithril prefetch 0, hit 0, accuracy: -nan, prefetch table size 0
SystemError: /opt/conda/conda-bld/python-split_1661469458365/work/Objects/longobject.c:506: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zzl/workfiles/projects/PyMimircache/test/test.py", line 27, in <module>
    print(run("../data/trace.txt"))
  File "/home/zzl/workfiles/projects/PyMimircache/test/test.py", line 24, in run
    hr = p.get_hit_rate()
  File "/home/zzl/local/anaconda3/lib/python3.9/site-packages/PyMimircache-0.0.2.103-py3.9-linux-x86_64.egg/PyMimircache/profiler/cGeneralProfiler.py", line 223, in get_hit_ratio
    self.hit_ratio = c_generalProfiler.get_hit_ratio(self.reader.c_reader,
SystemError: <built-in function get_hit_ratio> returned a result with an error set
```

for `amp`, I receive
```
cache size 9794
0.00%

AMP cache size 9794, hit rate 0.297913, prefetch 3850, hit 3732, accuracy: 0.969351

SystemError: /opt/conda/conda-bld/python-split_1661469458365/work/Objects/longobject.c:506: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zzl/workfiles/projects/PyMimircache/test/test.py", line 27, in <module>
    print(run("../data/trace.txt"))
  File "/home/zzl/workfiles/projects/PyMimircache/test/test.py", line 24, in run
    hr = p.get_hit_rate()
  File "/home/zzl/local/anaconda3/lib/python3.9/site-packages/PyMimircache-0.0.2.103-py3.9-linux-x86_64.egg/PyMimircache/profiler/cGeneralProfiler.py", line 223, in get_hit_ratio
    self.hit_ratio = c_generalProfiler.get_hit_ratio(self.reader.c_reader,
SystemError: <built-in function get_hit_ratio> returned a result with an error set
```

for `pg`, I receive
```
cache size 9794
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%

 PG cache size 9794, real size 8814, hit rate 0.282888, prefetch 87725, hit 9619, precision 0.109649
TypeError: bad argument type for built-in operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zzl/workfiles/projects/PyMimircache/test/test.py", line 27, in <module>
    print(run("../data/trace.txt"))
  File "/home/zzl/workfiles/projects/PyMimircache/test/test.py", line 24, in run
    hr = p.get_hit_rate()
  File "/home/zzl/local/anaconda3/lib/python3.9/site-packages/PyMimircache-0.0.2.103-py3.9-linux-x86_64.egg/PyMimircache/profiler/cGeneralProfiler.py", line 223, in get_hit_ratio
    self.hit_ratio = c_generalProfiler.get_hit_ratio(self.reader.c_reader,
SystemError: <built-in function get_hit_ratio> returned a result with an error set
```

**Comment by zztaki** [comment]
And `/opt/conda/conda-bld/python-split_1661469458365/work/Objects/longobject.c` does not exist on my server.

the GeneralProfiler.py is like that
```python3
def __bootstrap__():
    global __bootstrap__, __loader__, __file__
    import sys, pkg_resources, importlib.util
    __file__ = pkg_resources.resource_filename(__name__, 'GeneralProfiler.cpython-39-x86_64-linux-gnu.so')
    __loader__ = None; del __bootstrap__, __loader__
    spec = importlib.util.spec_from_file_location(__name__,__file__)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
__bootstrap__()

```

**Comment by zztaki** [comment]
I would be very grateful if I could get your help! 😄

**Comment by 1a1a11a** [comment]
Thank you for your interests! 
This library is no longer maintained, and I don't have time to debug this. But if you would like to, I can work with you adding the algorithms to libCacheSim

**Comment by zztaki** [comment]
> Thank you for your interests!
> This library is no longer maintained, and I don't have time to debug this. But if you would like to, I can work with you adding the algorithms to libCacheSim

Very cool! That is very exciting and meaningful. When I finish some work, I will try it!
